# Generated by Django 4.0.4 on 2024-07-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name_plural': 'actors'},
        ),
        migrations.AlterModelOptions(
            name='cinemahall',
            options={'verbose_name_plural': 'cinema_halls'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='moviesession',
            options={'ordering': ['-show_time'], 'verbose_name_plural': 'movies_sessions'},
        ),
    ]
